apiVersion: lifecycle.keptn.sh/v1beta1
kind: KeptnTaskDefinition
metadata:
  name: post-deployment-hello
  namespace: podtato-kubectl
spec:
  deno:
    inline:
      code: |
        console.log("Post-Deployment Task has been executed");
