apiVersion: v2
name: keptn-metrics-operator
description: A Helm chart for Keptn Metrics Operator, a subproject of Keptn
icon: >-
  https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg
home: https://keptn.sh
sources:
  - https://github.com/keptn/lifecycle-toolkit
keywords:
  - cloud-native
  - metrics
  - keptn
  - operator
  - analysis
annotations:
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn/lifecycle-toolkit/issues/new
    - name: community
      url: https://slack.keptn.sh/
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: 'true'
kubeVersion: '>= 1.24.0-0'
type: application
version: 2.0.0
appVersion: v1.0.1
dependencies:
  - name: common
    repository: https://charts.lifecycle.keptn.sh
    version: 0.2.1
