## @section Keptn Metrics Operator common
## @extra   operatorService.ports[0] webhook port (must correspond to Mutating Webhook Configurations)
## @param   operatorService.ports[0].name
## @param   operatorService.ports[0].port
## @param   operatorService.ports[0].protocol
## @param   operatorService.ports[0].targetPort
## @extra   operatorService.ports[1] port to integrate with the K8s custom metrics API
## @param   operatorService.ports[1].name
## @param   operatorService.ports[1].port
## @param   operatorService.ports[1].targetPort
## @extra   operatorService.ports[2] port to integrate with metrics API (e.g. Keda)
## @param   operatorService.ports[2].name
## @param   operatorService.ports[2].port
## @param   operatorService.ports[2].protocol
## @param   operatorService.ports[2].targetPort
## @param   operatorService.type
operatorService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - name: custom-metrics
      port: 443
      targetPort: custom-metrics
    - name: metrics
      port: 9999
      protocol: TCP
      targetPort: metrics
  type: ClusterIP

## @param      config.health.healthProbeBindAddress setup on what address to start the default health handler
## @param      config.leaderElection.leaderElect decides whether to enable leader election with multiple replicas
## @param      config.leaderElection.resourceName defines LeaderElectionID
## @param      config.metrics.bindAddress MetricsBindAddress is the TCP address that the controller should bind to for serving prometheus metrics. It can be set to "0" to disable the metrics serving.
## @param      config.webhook.port
config:
  health:
    healthProbeBindAddress: :8081
  leaderElection:
    leaderElect: true
    resourceName: 3f8532ca.keptn.sh
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443

## @extra Mutating Webhook Configurations for metrics Operator
## @param     webhookService.ports[0].port
## @param     webhookService.ports[0].protocol
## @param     webhookService.ports[0].targetPort
## @param     webhookService.type
webhookService:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  type: ClusterIP

## @param    nodeSelector add custom nodes selector to metrics operator
## @param   replicas customize number of installed metrics operator replicas
## @param    tolerations add custom tolerations to metrics operator
## @param    topologySpreadConstraints add custom topology constraints to metrics operator
nodeSelector: { }
replicas: 1
tolerations: [ ]
topologySpreadConstraints: [ ]

## @section Keptn Metrics Operator controller
## @extra   containerSecurityContext Sets security context privileges
## @param   containerSecurityContext.allowPrivilegeEscalation
## @param   containerSecurityContext.capabilities.drop
## @param   containerSecurityContext.privileged
## @param   containerSecurityContext.runAsGroup
## @param   containerSecurityContext.runAsNonRoot
## @param   containerSecurityContext.runAsUser
## @param   containerSecurityContext.seccompProfile.type
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault

## @param   env.exposeKeptnMetrics enable metrics exporter
## @param   env.enableKeptnAnalysis  enables/disables the analysis feature
## @param   env.metricsControllerLogLevel sets the log level of Metrics Controller
## @param   env.analysisControllerLogLevel  sets the log level of Analysis Controller
env:
  exposeKeptnMetrics: "true"
  enableKeptnAnalysis: "false"
  metricsControllerLogLevel: "0"
  analysisControllerLogLevel: "0"

## @param   image.repository specify registry for manager image
## @param   image.tag select tag for manager image
image:
  repository: ghcr.io/keptn/metrics-operator
  tag: v0.8.2

## @extra  livenessProbe custom livenessprobe for manager container
## @skip   livenessProbe.httpGet.path
## @skip   livenessProbe.httpGet.port
## @skip   livenessProbe.initialDelaySeconds
## @skip   livenessProbe.periodSeconds
livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

## @extra  readinessProbe custom readinessprobe for manager container
## @skip   readinessProbe.httpGet.path
## @skip   readinessProbe.httpGet.port
## @skip   readinessProbe.initialDelaySeconds
## @skip   readinessProbe.periodSeconds
readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

## @extra  resources specify limits and requests for manager container
## @skip   resources.limits.cpu
## @skip   resources.limits.memory
## @skip   resources.requests.cpu
## @skip   resources.requests.memory
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

## @section Global
## Current available parameters: kubernetesClusterDomain, imagePullSecrets, schedulingGatesEnabled
## @param  imagePullSecrets global value for image registry secret
## @param  kubernetesClusterDomain overrides domain.local
imagePullSecrets: [ ]
kubernetesClusterDomain: cluster.local