certManager:
  enabled: false
lifecycleOperator:
  enabled: false
metricsOperator:
  enabled: true
  image:
    tag: v0.0.0
  customMetricsAPIService:
    enabled: "false"

global:
  commonLabels:
    app.kubernetes.io/version: vmyversion
  caInjectionAnnotations:
    cert-manager.io/inject-ca-from: helmtests/keptn-certs