## @section Keptn
lifecycleOperator:
  ## @param lifecycleOperator.enabled Enable this value to install Keptn Lifecycle Operator
  enabled: true
metricsOperator:
  ## @param metricsOperator.enabled Enable this value to install Keptn Metrics Operator
  enabled: true

## @section Global parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

global:
  ## @param global.certManagerEnabled Enable this value to install Keptn Certificate Manager
  certManagerEnabled: true
  ## @param global.imageRegistry Global Docker image registry
  imageRegistry: "ghcr.io"

  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  ## @param global.imagePullPolicy Policy for pulling Docker images. Options: Always, IfNotPresent, Never
  imagePullPolicy: ""
  ## @param global.commonLabels Common labels to add to all Keptn resources. Evaluated as a template
  commonLabels: {}
  ## @param global.commonAnnotations Common annotations to add to all Keptn resources. Evaluated as a template
  commonAnnotations: {}
  ## @param global.caInjectionAnnotations CA injection annotations for cert-manager.io configuration
  caInjectionAnnotations: {}
