site_name: Keptn - Supercharge Your Deployments
theme:
  name: material
  custom_dir: docs-new/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/keptn-icon-white.svg
  favicon: https://lifecycle.keptn.sh/images/logo-mobile.svg
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
repo_name: keptn/lifecycle-toolkit
repo_url: https://github.com/keptn/lifecycle-toolkit
site_url: https://keptn.sh
edit_uri: edit/main/docs-new/
site_description: >-
  Achieve cloud-native application lifecycle orchestration with Keptn.
  Enhance Kubernetes monitoring, streamline metrics ingestion, and
  automate deployment validation. Join the Keptn community for insights.
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://keptn.sh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/keptnProject
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/keptnproject
    - icon: fontawesome/brands/github-alt
      link: https://github.com/keptn
    - icon: fontawesome/brands/slack
      link: https://cloud-native.slack.com/archives/C017GAX90GM
extra_javascript:
  - assets/javascripts/versions.js
extra_css:
  - assets/stylesheets/versions.css
plugins:
  - social
  - include-markdown:
      trailing_newlines: false
  - git-revision-date-localized

nav:
  - Home:
      - docs-new/index.md
  - Documentation:
      - docs-new/docs/index.md
