site_name: Keptn - Supercharge Your Deployments
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/keptn-icon-white.svg
  favicon: https://lifecycle.keptn.sh/images/logo-mobile.svg
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
repo_name: keptn/lifecycle-toolkit
repo_url: https://github.com/keptn/lifecycle-toolkit
site_url: https://lifecycle.keptn.sh
edit_uri: edit/main/docs/
site_description: >-
  Achieve cloud-native application lifecycle orchestration with Keptn.
  Enhance Kubernetes monitoring, streamline metrics ingestion, and
  automate deployment validation. Join the Keptn community for insights.
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://keptn.sh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/keptnProject
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/keptnproject
    - icon: fontawesome/brands/github-alt
      link: https://github.com/keptn
    - icon: fontawesome/brands/slack
      link: https://cloud-native.slack.com/archives/C017GAX90GM
extra_javascript:
  - assets/javascripts/versions.js
extra_css:
  - assets/stylesheets/versions.css
plugins:
  - social
  - include-markdown:
      trailing_newlines: false
  - git-revision-date-localized

nav:
  - Home:
      - index.md
  - Documentation:
      - docs/index.md
      - Tests: docs/tests.md
      - Core Concepts: docs/intro/index.md
      - Get Started:
          - docs/getting-started/index.md
          - Get started with Metrics: docs/getting-started/metrics.md
      - Installation:
          - docs/install/index.md
          - Install Keptn: docs/install/install.md
      - Guides:
          - docs/guides/index.md
          - Integrate Keptn with your Applications: docs/guides/integrate.md
          - Evaluations: docs/guides/evaluations.md
      - API Reference:
          - docs/crd-ref/index.md
          - Lifecycle API:
              - docs/crd-ref/lifecycle/index.md
              - v1alpha1: docs/crd-ref/lifecycle/v1alpha1/index.md
              - v1alpha2: docs/crd-ref/lifecycle/v1alpha2/index.md
              - v1alpha3: docs/crd-ref/lifecycle/v1alpha3/index.md
              - v1alpha4: docs/crd-ref/lifecycle/v1alpha4/index.md
  - Contributing:
      - contributing/index.md
      - Software Contributions:
          - contributing/software/index.md
          - Development Environment:
              - contributing/software/dev-env/index.md
  - Community:
      - community/index.md
