apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "common.labels.standard" ( dict "context" . ) | nindent 4 }}
