apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "common.labels.standard" ( dict "context" . ) | nindent 4 }}
{{- include  "common.annotations"  ( dict "context" . ) }}
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: 'metrics-operator-service'
    namespace: '{{ .Release.Namespace }}'
  version: v1beta2
  versionPriority: 200