apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetric
metadata:
  name: available-cpus
spec:
  provider:
    name: prometheus
  query: "sum(kube_pod_container_resource_limits{resource='cpu'}) - sum(kube_node_status_capacity{resource='cpu'})"
  fetchIntervalSeconds: 10
  range:
    interval: "5m"
