apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetricsProvider
metadata:
  name: keptnmetricsprovider-sample
spec:
  targetServer: "http://prometheus-k8s.monitoring.svc.cluster.local:9090" #string
  secretName: prometheusLoginCredentials #secret name, optional
