apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetric
metadata:
  labels:
    app.kubernetes.io/name: keptnmetric
    app.kubernetes.io/instance: keptnmetric-sample
    app.kubernetes.io/part-of: metrics-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metrics-operator
  name: keptnmetric-sample
spec:
  provider:
    name: some-name
  query: "sum(kube_pod_container_resource_limits{resource='cpu'}) - sum(kube_node_status_capacity{resource='cpu'})"
  fetchIntervalSeconds: 10
