apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: metrics-controller
  name: metrics-operator-service
  namespace: system
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - name: custom-metrics
      targetPort: custom-metrics
      port: 443
    - name: metrics
      protocol: TCP
      port: 9999
      targetPort: metrics
  selector:
    control-plane: metrics-operator
