# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/lifecycle.keptn.sh_keptntaskdefinitions.yaml
  - bases/lifecycle.keptn.sh_keptntasks.yaml
  - bases/lifecycle.keptn.sh_keptnapps.yaml
  - bases/lifecycle.keptn.sh_keptnworkloads.yaml
  - bases/lifecycle.keptn.sh_keptnworkloadinstances.yaml
  - bases/lifecycle.keptn.sh_keptnappversions.yaml
  - bases/lifecycle.keptn.sh_keptnevaluationdefinitions.yaml
  - bases/lifecycle.keptn.sh_keptnevaluationproviders.yaml
  - bases/lifecycle.keptn.sh_keptnevaluations.yaml
  - bases/options.keptn.sh_keptnconfigs.yaml
  - bases/lifecycle.keptn.sh_keptnappcreationrequests.yaml
# +kubebuilder:scaffold:crdkustomizeresource
# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: keptn-lifecycle-toolkit
      crdGroup: lifecycle.keptn.sh
      keptn.sh/inject-cert: "true"
patches:
  - path: patches/webhook_in_lifecycle_keptnapps.yaml
  - path: patches/webhook_in_lifecycle_keptnworkloadinstances.yaml
  - path: patches/webhook_in_lifecycle_keptnappversions.yaml
  - path: patches/webhook_in_lifecycle_keptnevaluationproviders.yaml
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# - path: patches/webhook_in_lifecycle_keptntaskdefinitions.yaml
# - path: patches/webhook_in_lifecycle_keptntasks.yaml
# - path: patches/webhook_in_lifecycle_keptnworkloads.yaml
# - path: patches/webhook_in_lifecycle_keptnevaluationdefinitions.yaml
# - path: patches/webhook_in_lifecycle_keptnevaluations.yaml
# - path: patches/webhook_in_options_keptnconfigs.yaml
# - path: patches/webhook_in_keptnappcreationrequests.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch
