apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# import the default deployment as the base
bases:
  - ../../operator/config/default/base
  - ../../klt-cert-manager/config/default
  - ../../scheduler/manifests/install
# replace the default namespace with {{ include "chart.namespace" . }}
# .Release.Namespace has not been used so that a custom _helpers.tpl file can maintain the expected behaviour of
# helm install -n
namespace: "{{ .Release.Namespace }}"
patchesStrategicMerge:
  - patches/patch_deployment.yaml

patches:
  - patch: |
      - op: replace
        path: '/spec/template/spec/containers/0/imagePullPolicy'
        value: "{{ .Values.deployment.imagePullPolicy}}"
    target:
      kind: Deployment
      name: "(controller-manager|cert-manager|keptn-scheduler)"