apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: certificate-operator-leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: certificate-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: certificate-operator
    namespace: system
