apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
# Compose all plugins in one profile
- schedulerName: keptn-scheduler
  plugins:
    multiPoint:
      enabled:
      - name: "KLCPermit"
      disabled: []
  pluginConfig: {}
