_merge: deep
title: Keptn

module:
  hugoVersion:
    extended: true
  imports:
    - path: github.com/keptn/docs-tooling
      ignoreConfig: false
      mounts:
        - source: static
          target: static
        - source: layouts
          target: layouts
        - source: data
          target: data
        - source: assets
          target: assets
        - source: archetypes
          target: archetypes
  proxy: direct
languages:
  en:
    title: Keptn
    contentDir: "content/en"
