_merge: deep
title: Keptn
baseURL: /

module:
  hugoVersion:
    extended: true
  imports:
    - disable: false
      path: github.com/google/docsy
    - disable: false
      path: github.com/google/docsy/dependencies
    - path: github.com/keptn/community
      ignoreConfig: false
      mounts:
        - source: ./
          target: ./content/community
          excludeFiles:
            - "mentorship"
        - source: "README.md"
          target: "./content/community/_index.md"
  proxy: direct

languages:
  en:
    title: Keptn
    contentDir: "content/en"

enableEmoji: true
enableGitInfo: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true

menu:
  main:
    - name: Keptn v1
      params:
        rel: external
      url: https://v1.keptn.sh/
      weight: 1
    - name: GitHub
      params:
        rel: external
      url: https://github.com/keptn/lifecycle-toolkit
      weight: 99

ignoreErrors:
  - "error-remote-getjson"

outputs:
  home:
    - HTML
  page:
    - HTML

permalinks: blog = "/:section/:year/:month/:day/:slug/"
taxonomies:
  category: categories
  tag: tags
