apiVersion: v2
name: keptn-lifecycle-operator
description: A Helm chart for Keptn Lifecycle Operator, a subproject of Keptn
icon: >-
  https://raw.githubusercontent.com/cncf/artwork/master/projects/keptn/icon/color/keptn-icon-color.svg
home: https://keptn.sh
sources:
  - https://github.com/keptn/lifecycle-toolkit
keywords:
  - cloud-native
  - lifecycle
  - lifecycle-management
  - application-lifecycle
  - application-lifecycle-management
  - orchestration
  - keptn
  - operator
  - pre-deployment
  - post-deployment
annotations:
  artifacthub.io/links: |
    - name: support
      url: https://github.com/keptn/lifecycle-toolkit/issues/new
    - name: community
      url: https://slack.keptn.sh/
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: 'true'
  artifacthub.io/operatorCapabilities: Full Lifecycle
kubeVersion: '>= 1.24.0-0'
type: application
version: 2.0.0
appVersion: v1.0.0
dependencies:
  - name: common
    repository: https://charts.lifecycle.keptn.sh
    version: 0.2.1
