# permissions for end users to view keptnworkloadinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnworkloadinstance-viewer-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnworkloadinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnworkloadinstances/status
  verbs:
  - get
