# permissions for end users to view keptnevaluationdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnevaluationdefinition-viewer-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevaluationdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevaluationdefinitions/status
  verbs:
  - get
