# permissions for end users to view keptnevaluationproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnevaluationprovider-viewer-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevaluationproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevaluationproviders/status
  verbs:
  - get
