# permissions for end users to view keptnapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnapp-viewer-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnapps/status
  verbs:
  - get
