# permissions for end users to edit keptntaskdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptntaskdefinition-editor-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptntaskdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptntaskdefinitions/status
  verbs:
  - get
