# permissions for end users to edit keptntasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptntask-editor-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptntasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptntasks/status
  verbs:
  - get
