{{- if or (le .Capabilities.KubeVersion.Minor "26") (not .Values.schedulingGatesEnabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extension-apiserver-authentication-reader
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "common.labels.standard" ( dict "context" . ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'extension-apiserver-authentication-reader'
subjects:
- kind: ServiceAccount
  name: 'keptn-scheduler'
  namespace: '{{ .Release.Namespace }}'
{{- end }}