# yamllint disable rule:line-length
## @section Keptn Scheduler
## @extra scheduler.scheduler.containerSecurityContext Sets security context
## @skip scheduler.scheduler.containerSecurityContext.allowPrivilegeEscalation
## @skip scheduler.scheduler.containerSecurityContext.capabilities.drop
## @skip scheduler.scheduler.containerSecurityContext.privileged
## @skip scheduler.scheduler.containerSecurityContext.readOnlyRootFilesystem
## @skip scheduler.scheduler.containerSecurityContext.runAsNonRoot
## @skip scheduler.scheduler.containerSecurityContext.runAsUser
## @skip scheduler.scheduler.containerSecurityContext.seccompProfile.type

## @param scheduler.scheduler.env.otelCollectorUrl sets url for open telemetry collector

## @param scheduler.scheduler.image.repository set image repository for scheduler
## @param scheduler.scheduler.image.tag set image tag for scheduler
## @param scheduler.scheduler.imagePullPolicy set image pull policy for scheduler

## @extra scheduler.scheduler.livenessProbe customizable liveness probe for the scheduler
## @skip scheduler.scheduler.livenessProbe.httpGet.path
## @skip scheduler.scheduler.livenessProbe.httpGet.port
## @skip scheduler.scheduler.livenessProbe.httpGet.scheme
## @skip scheduler.scheduler.livenessProbe.initialDelaySeconds

## @extra scheduler.scheduler.readinessProbe customizable readiness probe for the scheduler
## @skip scheduler.scheduler.readinessProbe.httpGet.path
## @skip scheduler.scheduler.readinessProbe.httpGet.port
## @skip scheduler.scheduler.readinessProbe.httpGet.scheme

## @extra scheduler.scheduler.resources sets cpu and memory resurces/limits for scheduler
## @skip scheduler.scheduler.resources.limits.cpu
## @skip scheduler.scheduler.resources.limits.memory
## @skip scheduler.scheduler.resources.requests.cpu
## @skip scheduler.scheduler.resources.requests.memory

## @param  schedulerConfig.schedulerConfigYaml.leaderElection.leaderElect enables leader election for multiple replicas of the scheduler
## @param  schedulerConfig.schedulerConfigYaml.profiles[0].plugins.permit.enabled[0].name enables permit plugin
## @param  schedulerConfig.schedulerConfigYaml.profiles[0].schedulerName changes scheduler name

## @param scheduler.nodeSelector adds node selectors for scheduler
## @param scheduler.replicas modifies replicas
## @param scheduler.tolerations adds tolerations for scheduler
## @param scheduler.topologySpreadConstraints add topology constraints for scheduler

## @section Keptn Certificate Operator common

## @param     certificateOperator.replicas customize number of replicas

## @param     certificateOperator.nodeSelector specify custom node selectors for cert manager
## @param     certificateOperator.tolerations customize tolerations for cert manager
## @param     certificateOperator.topologySpreadConstraints add topology constraints for cert manager

## @param    lifecycleManagerConfig.controllerManagerConfigYaml.health.healthProbeBindAddress setup on what address to start the default health handler
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.leaderElection.leaderElect enable leader election for multiple replicas of the lifecycle operator
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.leaderElection.resourceName define LeaderElectionID
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.metrics.bindAddress MetricsBindAddress is the TCP address that the controller should bind to for serving prometheus metrics. It can be set to "0" to disable the metrics serving.
## @param    lifecycleManagerConfig.controllerManagerConfigYaml.webhook.port setup port for the lifecycle operator admission webhook


## @section Keptn Certificate Operator controller
## @extra    certificateOperator.manager.containerSecurityContext Sets security context for the cert manager
## @skip     certificateOperator.manager.containerSecurityContext.allowPrivilegeEscalation
## @skip     certificateOperator.manager.containerSecurityContext.capabilities.drop
## @skip     certificateOperator.manager.containerSecurityContext.readOnlyRootFilesystem
## @skip     certificateOperator.manager.containerSecurityContext.runAsGroup
## @skip     certificateOperator.manager.containerSecurityContext.runAsUser
## @skip     certificateOperator.manager.containerSecurityContext.seccompProfile.type

## @param     certificateOperator.manager.image.repository specify repo for manager image
## @param     certificateOperator.manager.image.tag select tag for manager container
## @param     certificateOperator.manager.imagePullPolicy select image pull policy for manager container

## @param     certificateOperator.manager.env.labelSelectorKey specify the label selector to find resources to generate certificates for
## @param     certificateOperator.manager.env.labelSelectorValue specify the value for the label selector

## @extra     certificateOperator.manager.livenessProbe custom RBAC proxy liveness probe
## @skip     certificateOperator.manager.livenessProbe.httpGet.path
## @skip     certificateOperator.manager.livenessProbe.httpGet.port
## @skip     certificateOperator.manager.livenessProbe.initialDelaySeconds
## @skip     certificateOperator.manager.livenessProbe.periodSeconds

## @extra    certificateOperator.manager.readinessProbe custom manager readiness probe
## @skip     certificateOperator.manager.readinessProbe.httpGet.path
## @skip     certificateOperator.manager.readinessProbe.httpGet.port
## @skip     certificateOperator.manager.readinessProbe.initialDelaySeconds
## @skip     certificateOperator.manager.readinessProbe.periodSeconds

## @extra    certificateOperator.manager.resources custom limits and requests for manager container
## @skip     certificateOperator.manager.resources.limits.cpu
## @skip     certificateOperator.manager.resources.limits.memory
## @skip     certificateOperator.manager.resources.requests.cpu
## @skip     certificateOperator.manager.resources.requests.memory

## @section Keptn Lifecycle Operator common

## @param   lifecycleOperator.replicas customize number of installed lifecycle operator replicas

## @extra   lifecycleOperatorMetricsService Adjust settings here to change the k8s service for scraping Prometheus metrics
## @skip    lifecycleOperatorMetricsService.ports[0].name
## @skip    lifecycleOperatorMetricsService.ports[0].port
## @skip    lifecycleOperatorMetricsService.ports[0].protocol
## @skip    lifecycleOperatorMetricsService.ports[0].targetPort
## @skip    lifecycleOperatorMetricsService.type

## @extra    lifecycleWebhookService Mutating Webhook Configurations for lifecycle Operator
## @param    lifecycleWebhookService.ports[0].port
## @param    lifecycleWebhookService.ports[0].protocol
## @param    lifecycleWebhookService.ports[0].targetPort
## @param    lifecycleWebhookService.type

## @param   lifecycleOperator.nodeSelector add custom nodes selector to lifecycle operator
## @param   lifecycleOperator.tolerations add custom tolerations to lifecycle operator
## @param   lifecycleOperator.topologySpreadConstraints add custom topology constraints to lifecycle operator

## @section Keptn Lifecycle Operator controller
## @extra   lifecycleOperator.manager.containerSecurityContext Sets security context privileges
## @param   lifecycleOperator.manager.containerSecurityContext.allowPrivilegeEscalation
## @param   lifecycleOperator.manager.containerSecurityContext.capabilities.drop
## @param   lifecycleOperator.manager.containerSecurityContext.privileged
## @param   lifecycleOperator.manager.containerSecurityContext.runAsGroup
## @param   lifecycleOperator.manager.containerSecurityContext.runAsNonRoot
## @param   lifecycleOperator.manager.containerSecurityContext.runAsUser
## @param   lifecycleOperator.manager.containerSecurityContext.seccompProfile.type

## @param   lifecycleOperator.manager.env.keptnAppControllerLogLevel sets the log level of Keptn App Controller
## @param   lifecycleOperator.manager.env.keptnAppCreationRequestControllerLogLevel sets the log level of Keptn App Creation Request Controller
## @param   lifecycleOperator.manager.env.keptnAppVersionControllerLogLevel sets the log level of Keptn AppVersion Controller
## @param   lifecycleOperator.manager.env.keptnEvaluationControllerLogLevel sets the log level of Keptn Evaluation Controller
## @param   lifecycleOperator.manager.env.keptnTaskControllerLogLevel sets the log level of Keptn Task Controller
## @param   lifecycleOperator.manager.env.keptnTaskDefinitionControllerLogLevel sets the log level of Keptn TaskDefinition Controller
## @param   lifecycleOperator.manager.env.keptnWorkloadControllerLogLevel sets the log level of Keptn Workload Controller
## @param   lifecycleOperator.manager.env.keptnWorkloadInstanceControllerLogLevel sets the log level of Keptn WorkloadInstance Controller
## @param   lifecycleOperator.manager.env.optionsControllerLogLevel sets the log level of Keptn Options Controller

## @param   lifecycleOperator.manager.env.otelCollectorUrl Sets the URL for the open telemetry collector
## @param   lifecycleOperator.manager.env.functionRunnerImage specify image for deno task runtime
## @param   lifecycleOperator.manager.env.pythonRunnerImage specify image for python task runtime

## @param   lifecycleOperator.manager.image.repository specify registry for manager image
## @param   lifecycleOperator.manager.image.tag  select tag for manager image
## @param   lifecycleOperator.manager.imagePullPolicy specify pull policy for manager image

## @extra  lifecycleOperator.manager.livenessProbe custom livenessprobe for manager container
## @skip   lifecycleOperator.manager.livenessProbe.httpGet.path
## @skip   lifecycleOperator.manager.livenessProbe.httpGet.port
## @skip   lifecycleOperator.manager.livenessProbe.initialDelaySeconds
## @skip   lifecycleOperator.manager.livenessProbe.periodSeconds

## @extra  lifecycleOperator.manager.readinessProbe custom readinessprobe for manager container
## @skip   lifecycleOperator.manager.readinessProbe.httpGet.path
## @skip   lifecycleOperator.manager.readinessProbe.httpGet.port
## @skip   lifecycleOperator.manager.readinessProbe.initialDelaySeconds
## @skip   lifecycleOperator.manager.readinessProbe.periodSeconds

## @extra  lifecycleOperator.manager.resources specify limits and requests for manager container
## @skip   lifecycleOperator.manager.resources.limits.cpu
## @skip   lifecycleOperator.manager.resources.limits.memory
## @skip   lifecycleOperator.manager.resources.requests.cpu
## @skip   lifecycleOperator.manager.resources.requests.memory


## @section Keptn Metrics Operator common

## @param   metricsOperator.replicas customize number of installed metrics operator replicas

## @extra   metricsOperatorService.ports[0] webhook port (must correspond to Mutating Webhook Configurations)
## @param   metricsOperatorService.ports[0].name
## @param   metricsOperatorService.ports[0].port
## @param   metricsOperatorService.ports[0].protocol
## @param   metricsOperatorService.ports[0].targetPort
## @extra   metricsOperatorService.ports[1] port to integrate with the K8s custom metrics API
## @param   metricsOperatorService.ports[1].name
## @param   metricsOperatorService.ports[1].port
## @param   metricsOperatorService.ports[1].targetPort
## @extra   metricsOperatorService.ports[2] port to integrate with metrics API (e.g. Keda)
## @param   metricsOperatorService.ports[2].name
## @param   metricsOperatorService.ports[2].port
## @param   metricsOperatorService.ports[2].protocol
## @param   metricsOperatorService.ports[2].targetPort
## @param   metricsOperatorService.type

## @param      metricsManagerConfig.controllerManagerConfigYaml.health.healthProbeBindAddress setup on what address to start the default health handler
## @param      metricsManagerConfig.controllerManagerConfigYaml.leaderElection.leaderElect decides whether to enable leader election with multiple replicas
## @param      metricsManagerConfig.controllerManagerConfigYaml.leaderElection.resourceName defines LeaderElectionID
## @param      metricsManagerConfig.controllerManagerConfigYaml.metrics.bindAddress MetricsBindAddress is the TCP address that the controller should bind to for serving prometheus metrics. It can be set to "0" to disable the metrics serving.
## @param      metricsManagerConfig.controllerManagerConfigYaml.webhook.port

## @extra Mutating Webhook Configurations for metrics Operator
## @param     metricsWebhookService.ports[0].port
## @param     metricsWebhookService.ports[0].protocol
## @param     metricsWebhookService.ports[0].targetPort
## @param     metricsWebhookService.type

## @param    metricsOperator.nodeSelector add custom nodes selector to metrics operator
## @param    metricsOperator.tolerations add custom tolerations to metrics operator
## @param    metricsOperator.topologySpreadConstraints add custom topology constraints to metrics operator

## @section Keptn Metrics Operator controller
## @extra   metricsOperator.manager.containerSecurityContext Sets security context privileges
## @param   metricsOperator.manager.containerSecurityContext.allowPrivilegeEscalation
## @param   metricsOperator.manager.containerSecurityContext.capabilities.drop
## @param   metricsOperator.manager.containerSecurityContext.privileged
## @param   metricsOperator.manager.containerSecurityContext.runAsGroup
## @param   metricsOperator.manager.containerSecurityContext.runAsNonRoot
## @param   metricsOperator.manager.containerSecurityContext.runAsUser
## @param   metricsOperator.manager.containerSecurityContext.seccompProfile.type


## @param   metricsOperator.manager.image.repository specify registry for manager image
## @param   metricsOperator.manager.image.tag select tag for manager image

## @param   metricsOperator.manager.env.exposeKeptnMetrics enable metrics exporter
## @param   metricsOperator.manager.env.metricsControllerLogLevel sets the log level of Metrics Controller
## @param   metricsOperator.manager.env.analysisControllerLogLevel  sets the log level of Analysis Controller
## @param   metricsOperator.manager.env.enableKeptnAnalysis  enable/disables the analysis feature

## @extra  metricsOperator.manager.livenessProbe custom livenessprobe for manager container
## @skip   metricsOperator.manager.livenessProbe.httpGet.path
## @skip   metricsOperator.manager.livenessProbe.httpGet.port
## @skip   metricsOperator.manager.livenessProbe.initialDelaySeconds
## @skip   metricsOperator.manager.livenessProbe.periodSeconds

## @extra  metricsOperator.manager.readinessProbe custom readinessprobe for manager container
## @skip   metricsOperator.manager.readinessProbe.httpGet.path
## @skip   metricsOperator.manager.readinessProbe.httpGet.port
## @skip   metricsOperator.manager.readinessProbe.initialDelaySeconds
## @skip   metricsOperator.manager.readinessProbe.periodSeconds

## @extra  metricsOperator.manager.resources specify limits and requests for manager container
## @skip   metricsOperator.manager.resources.limits.cpu
## @skip   metricsOperator.manager.resources.limits.memory
## @skip   metricsOperator.manager.resources.requests.cpu
## @skip   metricsOperator.manager.resources.requests.memory


## @section Global
## Current available parameters: kubernetesClusterDomain, imagePullSecrets
## @param  kubernetesClusterDomain overrides domain.local
## @param  imagePullSecrets global value for image registry secret
