certificateOperator:
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: ghcr.keptn.sh/keptn/certificate-operator
      tag: v0.7.0
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      limits:
        cpu: 25m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 16Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
lifecycleManagerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: 6b866dd9.keptn.sh
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
lifecycleOperator:
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    env:
      functionRunnerImage: ghcr.keptn.sh/keptn/functions-runtime:v0.7.0
      keptnAppControllerLogLevel: "0"
      keptnAppVersionControllerLogLevel: "0"
      keptnEvaluationControllerLogLevel: "0"
      keptnTaskControllerLogLevel: "0"
      keptnTaskDefinitionControllerLogLevel: "0"
      keptnWorkloadControllerLogLevel: "0"
      keptnWorkloadInstanceControllerLogLevel: "0"
      optionsControllerLogLevel: "0"
    image:
      repository: ghcr.keptn.sh/keptn/lifecycle-operator
      tag: v0.7.0
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
lifecycleOperatorMetricsService:
  ports:
  - name: metrics
    port: 2222
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
lifecycleWebhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
metricsManagerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: 3f8532ca.keptn.sh
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsOperator:
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      exposeKeptnMetrics: "true"
      metricsControllerLogLevel: "0"
    image:
      repository: ghcr.keptn.sh/keptn/metrics-operator
      tag: v0.7.0
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8081
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8081
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
metricsOperatorService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  - name: custom-metrics
    port: 443
    targetPort: custom-metrics
  - name: metrics
    port: 9999
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
metricsWebhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
scheduler:
  nodeSelector: {}
  replicas: 1
  scheduler:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
    env:
      otelCollectorUrl: otel-collector:4317
    image:
      repository: ghcr.keptn.sh/keptn/scheduler
      tag: v0.7.0
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 15
    readinessProbe:
      httpGet:
        path: /healthz
        port: 10259
        scheme: HTTPS
    resources:
      limits:
        cpu: 300m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 20Mi
  tolerations: []
  topologySpreadConstraints: []
schedulerConfig:
  schedulerConfigYaml:
    leaderElection:
      leaderElect: false
    profiles:
    - plugins:
        permit:
          enabled:
          - name: KLCPermit
      schedulerName: keptn-scheduler
