## @section OpenTelemetry
otelCollector:
  ## @param otelCollector.url Sets the URL for the open telemetry collector
  url: "otel-collector:4317"

deployment:
  ## @param deployment.imagePullPolicy Sets the image pull policy for kubernetes deployment
  imagePullPolicy: "Always"
