apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: certificate-operator-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: certificate-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certificate-operator-role
subjects:
  - kind: ServiceAccount
    name: certificate-operator
    namespace: system
