## @section Global parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

##
global:
  ## @param global.imageRegistry Global container image registry
  imageRegistry: ""

  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  ## @param global.commonLabels Common annotations to add to all Keptn resources. Evaluated as a template
  commonLabels: {}
  ## @param global.commonAnnotations Common annotations to add to all Keptn resources. Evaluated as a template
  commonAnnotations: {}


# yamllint disable rule:line-length
## @section Keptn Certificate Operator common
## @param     nodeSelector specify custom node selectors for cert manager
nodeSelector: {}
## @param     replicas customize number of replicas
replicas: 1
## @param     tolerations customize tolerations for cert manager
tolerations: []
## @param     topologySpreadConstraints add topology constraints for cert manager
topologySpreadConstraints: []

## @param     kubernetesClusterDomain overrides cluster.local
kubernetesClusterDomain: cluster.local
## @param     annotations add deployment level annotations
annotations: {}
## @param     podAnnotations adds pod level annotations
podAnnotations: {}

## @section Keptn Certificate Operator controller
## @extra    containerSecurityContext Sets security context for the cert manager
## @skip     containerSecurityContext.allowPrivilegeEscalation
## @skip     containerSecurityContext.capabilities.drop
## @skip     containerSecurityContext.readOnlyRootFilesystem
## @skip     containerSecurityContext.runAsGroup
## @skip     containerSecurityContext.runAsUser
## @skip     containerSecurityContext.seccompProfile.type
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
env:
## @param     env.labelSelectorKey specify the label selector to find resources to generate certificates for
  labelSelectorKey: keptn.sh/inject-cert
## @param     env.labelSelectorValue specify the value for the label selector
  labelSelectorValue: "true"
image:
## @param     image.registry specify repo for manager image
  registry: ghcr.io
## @param     image.repository specify repo for manager image
  repository: keptn/certificate-operator
## @param     image.tag select tag for manager container
  tag: v1.2.0 # x-release-please-version
## @param     imagePullPolicy select image pull policy for manager container
imagePullPolicy: Always

## @extra     livenessProbe custom RBAC proxy liveness probe
## @skip     livenessProbe.httpGet.path
## @skip     livenessProbe.httpGet.port
## @skip     livenessProbe.initialDelaySeconds
## @skip     livenessProbe.periodSeconds
livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

## @extra    readinessProbe custom manager readiness probe
## @skip     readinessProbe.httpGet.path
## @skip     readinessProbe.httpGet.port
## @skip     readinessProbe.initialDelaySeconds
## @skip     readinessProbe.periodSeconds
readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

## @extra    resources custom limits and requests for manager container
## @skip     resources.limits.cpu
## @skip     resources.limits.memory
## @skip     resources.requests.cpu
## @skip     resources.requests.memory
resources:
  limits:
    cpu: 25m
    memory: 64Mi
  requests:
    cpu: 5m
    memory: 16Mi
