resources:
- manager.yaml
- service.yaml
- config.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: lifecycle-manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |
    - op: replace
      path: '/spec/template/spec/containers/0/image'
      value: '${RELEASE_REGISTRY}/lifecycle-operator:${CHART_APPVERSION}'
  target:
    kind: Deployment
    name: lifecycle-operator
    namespace: system
