apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificate-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    {{- include "common.labels.standard" (dict "context" .) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'leader-election-role'
subjects:
- kind: ServiceAccount
  name: 'certificate-operator'
  namespace: '{{ .Release.Namespace }}'
