---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    control-plane: certificate-operator
  {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      control-plane: certificate-operator
    {{- include "cert-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: certificate-operator
      {{- include "cert-manager.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
        - args:
            - --leader-elect
          command:
            - /manager
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LABEL_SELECTOR_KEY
              value: {{ .Values.env.labelSelectorKey | quote }}
            - name: LABEL_SELECTOR_VALUE
              value: {{ .Values.env.labelSelectorValue | quote }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ .Values.kubernetesClusterDomain }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag
          | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: manager
          resources: {{- toYaml .Values.resources | nindent 10
          }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation
            }}
            capabilities: {{- include "tplvalues.render" (dict "value" .Values.containerSecurityContext.capabilities
            "context" $) | nindent 12 }}
            readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem
            }}
            runAsGroup: {{ .Values.containerSecurityContext.runAsGroup
            }}
            runAsUser: {{ .Values.containerSecurityContext.runAsUser
            }}
            seccompProfile: {{- include "tplvalues.render" (dict "value" .Values.containerSecurityContext.seccompProfile
            "context" $) | nindent 12 }}
        {{- if .Values.livenessProbe }}
          livenessProbe: {{- include "tplvalues.render" (dict "value" .Values.livenessProbe "context" $) | nindent 10 }}
         {{- else }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe: {{- include "tplvalues.render" (dict "value" .Values.readinessProbe "context" $) | nindent 10 }}
         {{- else }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
        {{- end }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: certificate-operator
      terminationGracePeriodSeconds: 10
{{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" $) | nindent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector: {{- include "tplvalues.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations: {{- include "tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
{{- end }}
