apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kuberentes.io/instance: certificate-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
  {{- include "chart.labels" . | nindent 4 }}
