apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    {{- include "common.labels.standard" ( dict "context" $ ) | nindent 4 }}
    {{- include  "common.annotations"  ( dict "context" . ) }}
