apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
  {{- include "cert-manager.labels" . | nindent 4 }}
