apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-lifecycle-webhook-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lifecycleWebhookService.type }}
  selector:
    control-plane: lifecycle-operator
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.lifecycleWebhookService.ports | toYaml | nindent 2 -}}