apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnEvent
metadata:
  name: event-sample
spec:
  service: Service12
  application: Application12
  job: 
    backoffLimit: 5
    activeDeadlineSeconds: 100
    template:
      spec:
        containers:
        - name: hello-world
          image: ubuntu:latest
          command: ["echo",  "Hello from Keptn"]
        restartPolicy: Never
