apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnAppVersion
metadata:
  labels:
    app.kubernetes.io/name: keptnappversion
    app.kubernetes.io/instance: keptnappversion-sample
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keptn-lifecycle-toolkit
  name: keptnappversion-sample
spec:
# TODO(user): Add fields here
