apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnComponent
metadata:
  name: service-test
spec:
  application: Application12
  preDeploymentCheck:
    job: 
      backoffLimit: 5
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: hello-world
            image: ubuntu:latest
            command: ["echo",  "Hello from Keptn"]
          restartPolicy: Never
