apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: keptntaskdefinition-sample-container
spec:
  container:
    name: testy-test
    image: busybox:1.36.0
    resources:
      limits:
        memory: "200Mi"
    command:
      - 'echo'
      - 'Hello World!'
      - '>'
      - '/cache/log.txt'
    volumeMounts:
      - mountPath: /cache
        name: logger
