apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnApp
metadata:
  labels:
    app.kubernetes.io/name: keptnapp
    app.kubernetes.io/instance: keptnapp-sample
    app.kubernetes.io/part-of: keptn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keptn
  name: keptnapp-sample
spec:
# TODO(user): Add fields here
