apiVersion: lifecycle.keptn.sh/v1beta1
kind: KeptnTask
metadata:
  name: keptntask-sample
spec:
  context:
    appName: podtato-head
    appVersion: '1.3'
    taskType: pre
  retries: 2
  taskDefinition: pre-task-retries
  timeout: 5m0s
status:
  message: Job has reached the specified backoff limit
  reason: BackoffLimitExceeded
  status: Failed
