---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: keptnevaluations.lifecycle.keptn.sh
spec:
  group: lifecycle.keptn.sh
  names:
    kind: KeptnEvaluation
    listKind: KeptnEvaluationList
    plural: keptnevaluations
    shortNames:
      - ke
    singular: keptnevaluation
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.appName
          name: AppName
          type: string
        - jsonPath: .spec.appVersion
          name: AppVersion
          type: string
        - jsonPath: .spec.workload
          name: WorkloadName
          type: string
        - jsonPath: .spec.workloadVersion
          name: WorkloadVersion
          type: string
        - jsonPath: .status.retryCount
          name: RetryCount
          type: string
        - jsonPath: .status.evaluationStatus
          name: EvaluationStatus
          type: string
        - jsonPath: .status.overallStatus
          name: OverallStatus
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: KeptnEvaluation is the Schema for the keptnevaluations API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: KeptnEvaluationSpec defines the desired state of KeptnEvaluation
              properties:
                appName:
                  type: string
                appVersion:
                  type: string
                checkType:
                  type: string
                evaluationDefinition:
                  type: string
                failAction:
                  type: string
                retries:
                  default: 10
                  type: integer
                retryInterval:
                  default: 5s
                  pattern: ^0|([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$
                  type: string
                workload:
                  type: string
                workloadVersion:
                  type: string
              required:
                - evaluationDefinition
                - workloadVersion
              type: object
            status:
              description: KeptnEvaluationStatus defines the observed state of KeptnEvaluation
              properties:
                endTime:
                  format: date-time
                  type: string
                evaluationStatus:
                  additionalProperties:
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                      value:
                        type: string
                    required:
                      - status
                      - value
                    type: object
                  type: object
                overallStatus:
                  default: Pending
                  type: string
                retryCount:
                  default: 0
                  type: integer
                startTime:
                  format: date-time
                  type: string
              required:
                - evaluationStatus
                - overallStatus
                - retryCount
              type: object
          type: object
      served: true
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .spec.appName
          name: AppName
          type: string
        - jsonPath: .spec.appVersion
          name: AppVersion
          type: string
        - jsonPath: .spec.workload
          name: WorkloadName
          type: string
        - jsonPath: .spec.workloadVersion
          name: WorkloadVersion
          type: string
        - jsonPath: .status.retryCount
          name: RetryCount
          type: string
        - jsonPath: .status.evaluationStatus
          name: EvaluationStatus
          type: string
        - jsonPath: .status.overallStatus
          name: OverallStatus
          type: string
      name: v1alpha2
      schema:
        openAPIV3Schema:
          description: KeptnEvaluation is the Schema for the keptnevaluations API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: KeptnEvaluationSpec defines the desired state of KeptnEvaluation
              properties:
                appName:
                  type: string
                appVersion:
                  type: string
                checkType:
                  type: string
                evaluationDefinition:
                  type: string
                failAction:
                  type: string
                retries:
                  default: 10
                  type: integer
                retryInterval:
                  default: 5s
                  pattern: ^0|([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$
                  type: string
                workload:
                  type: string
                workloadVersion:
                  type: string
              required:
                - evaluationDefinition
                - workloadVersion
              type: object
            status:
              description: KeptnEvaluationStatus defines the observed state of KeptnEvaluation
              properties:
                endTime:
                  format: date-time
                  type: string
                evaluationStatus:
                  additionalProperties:
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                      value:
                        type: string
                    required:
                      - status
                      - value
                    type: object
                  type: object
                overallStatus:
                  default: Pending
                  type: string
                retryCount:
                  default: 0
                  type: integer
                startTime:
                  format: date-time
                  type: string
              required:
                - evaluationStatus
                - overallStatus
                - retryCount
              type: object
          type: object
      served: true
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .spec.appName
          name: AppName
          type: string
        - jsonPath: .spec.appVersion
          name: AppVersion
          type: string
        - jsonPath: .spec.workload
          name: WorkloadName
          type: string
        - jsonPath: .spec.workloadVersion
          name: WorkloadVersion
          type: string
        - jsonPath: .status.retryCount
          name: RetryCount
          type: string
        - jsonPath: .status.evaluationStatus
          name: EvaluationStatus
          type: string
        - jsonPath: .status.overallStatus
          name: OverallStatus
          type: string
      name: v1alpha3
      schema:
        openAPIV3Schema:
          description: KeptnEvaluation is the Schema for the keptnevaluations API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: KeptnEvaluationSpec defines the desired state of KeptnEvaluation
              properties:
                appName:
                  type: string
                appVersion:
                  type: string
                checkType:
                  type: string
                evaluationDefinition:
                  type: string
                failAction:
                  type: string
                retries:
                  default: 10
                  type: integer
                retryInterval:
                  default: 5s
                  pattern: ^0|([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$
                  type: string
                workload:
                  type: string
                workloadVersion:
                  type: string
              required:
                - evaluationDefinition
                - workloadVersion
              type: object
            status:
              description: KeptnEvaluationStatus defines the observed state of KeptnEvaluation
              properties:
                endTime:
                  format: date-time
                  type: string
                evaluationStatus:
                  additionalProperties:
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                      value:
                        type: string
                    required:
                      - status
                      - value
                    type: object
                  type: object
                overallStatus:
                  default: Pending
                  type: string
                retryCount:
                  default: 0
                  type: integer
                startTime:
                  format: date-time
                  type: string
              required:
                - evaluationStatus
                - overallStatus
                - retryCount
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
