---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: keptntasks.lifecycle.keptn.sh
spec:
  group: lifecycle.keptn.sh
  names:
    kind: KeptnTask
    listKind: KeptnTaskList
    plural: keptntasks
    singular: keptntask
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.app
      name: AppName
      type: string
    - jsonPath: .spec.workload
      name: Workload
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .status.jobName
      name: Job Name
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KeptnTask is the Schema for the keptntasks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnTaskSpec defines the desired state of KeptnTask
            properties:
              app:
                type: string
              checkType:
                type: string
              parameters:
                properties:
                  map:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              secureParameters:
                properties:
                  secret:
                    type: string
                type: object
              taskDefinition:
                type: string
              version:
                type: string
              workload:
                type: string
            required:
            - taskDefinition
            - version
            type: object
          status:
            description: KeptnTaskStatus defines the observed state of KeptnTask
            properties:
              endTime:
                format: date-time
                type: string
              jobName:
                type: string
              startTime:
                format: date-time
                type: string
              status:
                default: Pending
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
