---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: keptnworkloadinstances.lifecycle.keptn.sh
spec:
  group: lifecycle.keptn.sh
  names:
    kind: KeptnWorkloadInstance
    listKind: KeptnWorkloadInstanceList
    plural: keptnworkloadinstances
    singular: keptnworkloadinstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.app
      name: AppName
      type: string
    - jsonPath: .spec.workloadName
      name: Workload
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .status.preDeploymentStatus
      name: PreDeploymentStatus
      type: string
    - jsonPath: .status.deploymentStatus
      name: DeploymentStatus
      type: string
    - jsonPath: .status.postDeploymentStatus
      name: PostDeploymentStatus
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KeptnWorkloadInstance is the Schema for the keptnworkloadinstances
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnWorkloadInstanceSpec defines the desired state of KeptnWorkloadInstance
            properties:
              app:
                type: string
              postDeploymentAnalysis:
                items:
                  type: string
                type: array
              postDeploymentTasks:
                items:
                  type: string
                type: array
              preDeploymentAnalysis:
                items:
                  type: string
                type: array
              preDeploymentTasks:
                items:
                  type: string
                type: array
              resourceReference:
                properties:
                  kind:
                    type: string
                  uid:
                    description: UID is a type that holds unique ID values, including
                      UUIDs.  Because we don't ONLY use UUIDs, this is an alias to
                      string.  Being a type captures intent and helps make sure that
                      UIDs and names do not get conflated.
                    type: string
                required:
                - kind
                - uid
                type: object
              tracecontext:
                additionalProperties:
                  type: string
                type: object
              version:
                type: string
              workloadName:
                type: string
            required:
            - app
            - resourceReference
            - version
            - workloadName
            type: object
          status:
            description: KeptnWorkloadInstanceStatus defines the observed state of
              KeptnWorkloadInstance
            properties:
              deploymentStatus:
                default: Pending
                type: string
              postDeploymentStatus:
                default: Pending
                type: string
              postDeploymentTaskStatus:
                items:
                  properties:
                    TaskDefinitionName:
                      type: string
                    status:
                      type: string
                    taskName:
                      type: string
                  type: object
                type: array
              preDeploymentStatus:
                default: Pending
                type: string
              preDeploymentTaskStatus:
                items:
                  properties:
                    TaskDefinitionName:
                      type: string
                    status:
                      type: string
                    taskName:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
