---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.4
  name: keptntaskdefinitions.lifecycle.keptn.sh
spec:
  group: lifecycle.keptn.sh
  names:
    kind: KeptnTaskDefinition
    listKind: KeptnTaskDefinitionList
    plural: keptntaskdefinitions
    singular: keptntaskdefinition
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KeptnTaskDefinition is the Schema for the keptntaskdefinitions
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnTaskDefinitionSpec defines the desired state of KeptnTaskDefinition
            properties:
              function:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
                    type: object
                  functionRef:
                    properties:
                      name:
                        type: string
                    type: object
                  httpRef:
                    properties:
                      url:
                        type: string
                    type: object
                  inline:
                    properties:
                      code:
                        type: string
                    type: object
                  parameters:
                    properties:
                      map:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  secureParameters:
                    properties:
                      secret:
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: KeptnTaskDefinitionStatus defines the observed state of KeptnTaskDefinition
            properties:
              function:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                properties:
                  configMap:
                    description: 'INSERT ADDITIONAL STATUS FIELD - define observed
                      state of cluster Important: Run "make" to regenerate code after
                      modifying this file'
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: KeptnTaskDefinition is the Schema for the keptntaskdefinitions
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnTaskDefinitionSpec defines the desired state of KeptnTaskDefinition
            properties:
              function:
                properties:
                  configMapRef:
                    properties:
                      name:
                        type: string
                    type: object
                  functionRef:
                    properties:
                      name:
                        type: string
                    type: object
                  httpRef:
                    properties:
                      url:
                        type: string
                    type: object
                  inline:
                    properties:
                      code:
                        type: string
                    type: object
                  parameters:
                    properties:
                      map:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  secureParameters:
                    properties:
                      secret:
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: KeptnTaskDefinitionStatus defines the observed state of KeptnTaskDefinition
            properties:
              function:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                properties:
                  configMap:
                    description: 'INSERT ADDITIONAL STATUS FIELD - define observed
                      state of cluster Important: Run "make" to regenerate code after
                      modifying this file'
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        description: KeptnTaskDefinition is the Schema for the keptntaskdefinitions
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec describes the desired state of the KeptnTaskDefinition
            properties:
              function:
                description: Function contains the definition for the function that
                  is to be executed in KeptnTasks based on the KeptnTaskDefinitions
                properties:
                  configMapRef:
                    description: ConfigMapReference allows to reference a ConfigMap
                      containing the code of the function. When referencing a ConfigMap,
                      the code of the function must be available as a value of the
                      'code' key of the referenced ConfigMap
                    properties:
                      name:
                        description: Name is the name of the referenced ConfigMap
                        type: string
                    type: object
                  functionRef:
                    description: FunctionReference allows to reference another KeptnTaskDefinition
                      which contains the source code of the function to be executes
                      for KeptnTasks based on this KeptnTaskDefinition. This can be
                      useful when you have multiple KeptnTaskDefinitions that should
                      execute the same logic, but each with different parameters.
                    properties:
                      name:
                        description: Name is the name of the referenced KeptnTaksDefinition
                        type: string
                    type: object
                  httpRef:
                    description: HttpReference allows to point to an HTTP URL containing
                      the code of the function.
                    properties:
                      url:
                        description: Url is the URL containing the code of the function
                        type: string
                    type: object
                  inline:
                    description: Inline allows to specify the code that should be
                      executed directly in the KeptnTaskDefinition, as a multi-line
                      string
                    properties:
                      code:
                        description: Code contains the code of the function
                        type: string
                    type: object
                  parameters:
                    description: Parameters contains parameters that will be passed
                      to the job that executes the task
                    properties:
                      map:
                        additionalProperties:
                          type: string
                        description: Inline contains the parameters that will be made
                          available to the job executing the KeptnTask via the 'DATA'
                          environment variable. The 'DATA'  environment variable's
                          content will be a json encoded string containing all properties
                          of the map provided
                        type: object
                    type: object
                  secureParameters:
                    description: SecureParameters contains secure parameters that
                      will be passed to the job that executes the task
                    properties:
                      secret:
                        description: Secret contains the parameters that will be made
                          available to the job executing the KeptnTask via the 'SECRET_DATA'
                          environment variable. The 'SECRET_DATA'  environment variable's
                          content will the same as value of the 'SECRET_DATA' key
                          of the referenced secret.
                        type: string
                    type: object
                type: object
              retries:
                default: 10
                description: Retries specifies how many times a job executing the
                  KeptnTaskDefinition should be restarted in the case of an unsuccessful
                  attempt
                format: int32
                type: integer
              timeout:
                default: 5m
                description: Timeout specifies the maximum time to wait for the task
                  to be completed successfully. If the task does not complete successfully
                  within this time frame, it will be considered to be failed.
                pattern: ^0|([0-9]+(\.[0-9]+)?(ns|us|Âµs|ms|s|m|h))+$
                type: string
            type: object
          status:
            description: Status describes the current state of the KeptnTaskDefinition
            properties:
              function:
                description: Function contains status information of the function
                  definition for the task
                properties:
                  configMap:
                    description: ConfigMap indicates the ConfigMap in which the function
                      code is stored
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
