---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: keptntasks.lifecycle.keptn.sh
spec:
  group: lifecycle.keptn.sh
  names:
    kind: KeptnTask
    listKind: KeptnTaskList
    plural: keptntasks
    singular: keptntask
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.app
      name: AppName
      type: string
    - jsonPath: .spec.appVersion
      name: AppVersion
      type: string
    - jsonPath: .spec.workload
      name: WorkloadName
      type: string
    - jsonPath: .spec.workloadVersion
      name: WorkloadVersion
      type: string
    - jsonPath: .status.jobName
      name: Job Name
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KeptnTask is the Schema for the keptntasks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnTaskSpec defines the desired state of KeptnTask
            properties:
              app:
                type: string
              appVersion:
                type: string
              checkType:
                type: string
              context:
                properties:
                  appName:
                    type: string
                  appVersion:
                    type: string
                  objectType:
                    type: string
                  taskType:
                    type: string
                  workloadName:
                    type: string
                  workloadVersion:
                    type: string
                required:
                - appName
                - appVersion
                - objectType
                - taskType
                - workloadName
                - workloadVersion
                type: object
              parameters:
                properties:
                  map:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              secureParameters:
                properties:
                  secret:
                    type: string
                type: object
              taskDefinition:
                type: string
              workload:
                type: string
              workloadVersion:
                type: string
            required:
            - app
            - appVersion
            - context
            - taskDefinition
            - workload
            - workloadVersion
            type: object
          status:
            description: KeptnTaskStatus defines the observed state of KeptnTask
            properties:
              endTime:
                format: date-time
                type: string
              jobName:
                type: string
              message:
                type: string
              startTime:
                format: date-time
                type: string
              status:
                default: Pending
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .spec.app
      name: AppName
      type: string
    - jsonPath: .spec.appVersion
      name: AppVersion
      type: string
    - jsonPath: .spec.workload
      name: WorkloadName
      type: string
    - jsonPath: .spec.workloadVersion
      name: WorkloadVersion
      type: string
    - jsonPath: .status.jobName
      name: Job Name
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: KeptnTask is the Schema for the keptntasks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnTaskSpec defines the desired state of KeptnTask
            properties:
              app:
                type: string
              appVersion:
                type: string
              checkType:
                type: string
              context:
                properties:
                  appName:
                    type: string
                  appVersion:
                    type: string
                  objectType:
                    type: string
                  taskType:
                    type: string
                  workloadName:
                    type: string
                  workloadVersion:
                    type: string
                required:
                - appName
                - appVersion
                - objectType
                - taskType
                - workloadName
                - workloadVersion
                type: object
              parameters:
                properties:
                  map:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              secureParameters:
                properties:
                  secret:
                    type: string
                type: object
              taskDefinition:
                type: string
              workload:
                type: string
              workloadVersion:
                type: string
            required:
            - app
            - appVersion
            - context
            - taskDefinition
            - workload
            - workloadVersion
            type: object
          status:
            description: KeptnTaskStatus defines the observed state of KeptnTask
            properties:
              endTime:
                format: date-time
                type: string
              jobName:
                type: string
              message:
                type: string
              startTime:
                format: date-time
                type: string
              status:
                default: Pending
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .spec.app
      name: AppName
      type: string
    - jsonPath: .spec.appVersion
      name: AppVersion
      type: string
    - jsonPath: .spec.workload
      name: WorkloadName
      type: string
    - jsonPath: .spec.workloadVersion
      name: WorkloadVersion
      type: string
    - jsonPath: .status.jobName
      name: Job Name
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha3
    schema:
      openAPIV3Schema:
        description: KeptnTask is the Schema for the keptntasks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KeptnTaskSpec defines the desired state of KeptnTask
            properties:
              app:
                type: string
              appVersion:
                type: string
              checkType:
                type: string
              context:
                properties:
                  appName:
                    type: string
                  appVersion:
                    type: string
                  objectType:
                    type: string
                  taskType:
                    type: string
                  workloadName:
                    type: string
                  workloadVersion:
                    type: string
                required:
                - appName
                - appVersion
                - objectType
                - taskType
                - workloadName
                - workloadVersion
                type: object
              parameters:
                properties:
                  map:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              retries:
                default: 10
                format: int32
                type: integer
              secureParameters:
                properties:
                  secret:
                    type: string
                type: object
              taskDefinition:
                type: string
              timeout:
                default: 5m
                pattern: ^0|([0-9]+(\.[0-9]+)?(ns|us|Âµs|ms|s|m|h))+$
                type: string
              workload:
                type: string
              workloadVersion:
                type: string
            required:
            - app
            - appVersion
            - context
            - taskDefinition
            - workload
            - workloadVersion
            type: object
          status:
            description: KeptnTaskStatus defines the observed state of KeptnTask
            properties:
              endTime:
                format: date-time
                type: string
              jobName:
                type: string
              message:
                type: string
              reason:
                type: string
              startTime:
                format: date-time
                type: string
              status:
                default: Pending
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
