name: Spell Checker
on:
  pull_request_target:
    branches:
      - "main"
      - "page"
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

# Declare default permissions as read only.
permissions: read-all

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-22.04
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@00c989c97749eb0cb2d256bdc55ac61b0096c6d3 # v0.0.22
        with:
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' && 1 }}
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@main
          post_comment: 0
          use_magic_file: 1
          report-timing: 1
          warnings:
            bad-regex
            binary-file
            deprecated-feature
            large-file
            limited-references
            no-newline-at-eof
            noisy-file
            non-alpha-in-dictionary
            token-is-substring
            unexpected-line-ending
            whitespace-in-dictionary
            minified-file
            unsupported-configuration
            no-files-to-check
          use_sarif: false
          extra_dictionary_limit: 20
          extra_dictionaries:
            cspell:software-terms/dict/softwareTerms.txt
            cspell:k8s/dict/k8s.txt
            cspell:golang/dict/go.txt
            cspell:html/dict/html.txt
