# permissions for end users to edit keptnconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keptnconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keptn-lifecycle-toolkit
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: keptnconfig-editor-role
rules:
  - apiGroups:
      - options.keptn.sh
    resources:
      - keptnconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - options.keptn.sh
    resources:
      - keptnconfigs/status
    verbs:
      - get
